---
version: "3.9"
services:
  frontend:
    build: .
    depends_on:
      - redis
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development

  redis:
    image: "redis:alpine"
